name: Re-generate list
on:
  push:
    branches:
      - master
  pull_request:

jobs:
  generate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Say hi
        run: |
          echo 'meow'
          echo 'alllright'
          echo "::set-output name=random-id::$(echo $RANDOM)"
          echo "::warning file=wow.py,line=1,col=2::Missing semicolon"
          echo "::error file=wow.py,line=3,col=2::Something went wrong"
          echo 'alllright'
          echo 'alllright'
          echo 'alllright'
          echo 'alllright'
          echo 'alllright'
          echo 'alllright'
          echo 'alllright'

    outputs:
      random: "ok"
      sum: "wow"